Repository AY2425S1-CS2103T-F10-1/tp, pull requests merged in 2024-10, with the labels that each got.

#40 Update about us
  docs/AboutUs.md
  docs/images/l-rrrr.png
Labels: priority.Low

#43 Refactor code to include a new field Client Type
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/clienttype/ClientType.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/clienttype/TagTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#45 Add Description Class
  src/main/java/seedu/address/model/description/Description.java
Labels: priority.High

#54 Update checkstyle
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ClientHubTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Low

#56 Update tag to clientType
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/clienttype/ClientType.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedClientType.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#63 Create new findPhone feature
  src/main/java/seedu/address/logic/commands/FindPhoneCommand.java
  src/main/java/seedu/address/logic/parser/ClientHubParser.java
  src/main/java/seedu/address/logic/parser/FindPhoneCommandParser.java
  src/main/java/seedu/address/model/person/PhoneBeginsWithKeywordPredicate.java
  src/test/java/seedu/address/logic/commands/FindPhoneCommandTest.java
  src/test/java/seedu/address/logic/parser/ClientHubParserTest.java
  src/test/java/seedu/address/logic/parser/FindPhoneCommandParserTest.java
  src/test/java/seedu/address/model/person/PhoneBeginsWithKeywordPredicateTest.java
Labels: priority.Medium

#64 Add FindClientType Command
  src/main/java/seedu/address/logic/commands/FindClientTypeCommand.java
  src/main/java/seedu/address/logic/parser/ClientHubParser.java
  src/main/java/seedu/address/logic/parser/FindClientTypeCommandParser.java
  src/main/java/seedu/address/model/person/ClientTypeContainsKeywordsPredicate.java
Labels: priority.Medium

#68 Update FindNameCommand
  src/main/java/seedu/address/logic/commands/FindNameCommand.java
  src/main/java/seedu/address/logic/parser/ClientHubParser.java
  src/main/java/seedu/address/logic/parser/FindNameCommandParser.java
Labels: priority.Medium

#71 Debug failed test cases
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#75 Added Find Phone
  docs/UserGuide.md
Labels: priority.Low

#79 Update UserGuide for FindAddress
  docs/UserGuide.md
  docs/images/findTampines.png
Labels: priority.Medium

#81 Update User guide
  docs/UserGuide.md
Labels: priority.Low

#90 Update Messages.java
  src/main/java/seedu/address/logic/Messages.java
Labels: priority.Low

#92 Update user guide pictures
  docs/AboutUs.md
  docs/UserGuide.md
  docs/_config.yml
  docs/images/find9234Result.png
Labels: priority.Low

#94 Update FindAddress Command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/FindAddressCommandParser.java
  src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindAddressCommandTest.java
  src/test/java/seedu/address/logic/parser/ClientHubParserTest.java
  src/test/java/seedu/address/logic/parser/FindAddressCommandParserTest.java
  src/test/java/seedu/address/model/person/AddressContainsKeywordsPredicateTest.java
Labels: priority.Medium

#96 Update UML diagram
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram-Model.puml
  docs/diagrams/tracing/LogicSequenceDiagram.puml
Labels: priority.Low

#102 Update FindClientType command
  src/main/java/seedu/address/model/person/ClientTypeContainsKeywordsPredicate.java
Labels: priority.Low

#101 Update Commands
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ClientHubParser.java
  src/test/java/seedu/address/logic/parser/ClientHubParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.Low

#108 Branch update fn command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindNameCommand.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindNameCommandTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: priority.Medium

#106 Update UserGuide for FindClientType Command
  docs/UserGuide.md
Labels: priority.Low

#112 Delete command errorfix
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsDeletePredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/data/JsonSerializableClientHubTest/typicalPersonsClientHub.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/ClientHubParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsDeletePredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#115 Add View Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/ClientHubParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/person/exceptions/PersonNotFoundException.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ViewPersonWindow.java
  src/main/resources/view/ViewPersonWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/ClientHubParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: priority.High

#113 Create sort feature by name
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindAddressCommand.java
  src/main/java/seedu/address/logic/commands/FindClientTypeCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindNameCommand.java
  src/main/java/seedu/address/logic/commands/FindPhoneCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/ClientHubParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/NameComparator.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindAddressCommandTest.java
  src/test/java/seedu/address/logic/commands/FindClientTypeCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindNameCommandTest.java
  src/test/java/seedu/address/logic/commands/FindPhoneCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/ClientHubParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameComparatorTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: priority.High

#119 Update README
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: priority.Medium

#123 Update View Command in UG
  docs/UserGuide.md
  docs/images/viewCommandExample.png
Labels: priority.Low

#124 Update user guide to include Sort Command
  docs/UserGuide.md
Labels: priority.Medium

#126 Add short form to sort command
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/ClientHubParser.java
  src/test/java/seedu/address/logic/parser/ClientHubParserTest.java
Labels: priority.Low

#127 Update UI for MainWindow and ViewPersonWindow
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ViewPersonWindow.css
  src/main/resources/view/ViewPersonWindow.fxml
Labels: priority.Medium

#129 Enable assertions
  build.gradle
Labels: priority.Low

#132 Update developer guide regarding model
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: priority.Medium

#139 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: priority.Medium

#140 Clean up unnecessary lines of code
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.Low

#142 Update UG
  docs/UserGuide.md
Labels: priority.Low

#144 Update description and clientType
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Description.java
  src/test/data/JsonClientHubStorageTest/invalidPersonClientHub.json
  src/test/data/JsonSerializableClientHubTest/invalidPersonClientHub.json
  src/test/data/JsonSerializableClientHubTest/typicalPersonsClientHub.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/DescriptionTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.Medium

#146 Refine UG
  docs/UserGuide.md
Labels: priority.Low

#147 Branch update help
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#151 Branch update guides
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
Labels: priority.Medium

#156 Refine HelpWindow UI
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: priority.Low

#158 Fix unupdated UML diagrams in DG
  docs/diagrams/ParserClasses.puml
  docs/images/ParserClasses.png
Labels: priority.Medium

#160 Add Tests
  docs/diagrams/LogicClassDiagram.puml
  src/main/java/seedu/address/model/person/Description.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/model/person/DescriptionTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsDeletePredicateTest.java
Labels: priority.Medium

#164 Refine ViewCommand
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
Labels: priority.Medium

#165 Add shortcut command for ViewCommand
  src/main/java/seedu/address/logic/parser/ClientHubParser.java
  src/test/java/seedu/address/logic/parser/ClientHubParserTest.java
Labels: priority.Low

#166 Update Sort command to latest version
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/ClientHubParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/ClientHubParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: priority.High

#169 Update code with new reminder logic
  src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
  src/main/java/seedu/address/logic/commands/reminder/DeleteReminderCommand.java
  src/main/java/seedu/address/logic/commands/reminder/EditReminderCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/reminder/AddReminderParser.java
  src/main/java/seedu/address/logic/parser/reminder/DeleteReminderParser.java
  src/main/java/seedu/address/logic/parser/reminder/EditReminderParser.java
  src/main/java/seedu/address/model/reminder/Reminder.java
  src/main/java/seedu/address/model/reminder/ReminderDescription.java
Labels: priority.High

#171 Update baseline of remainder
  src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
  src/main/java/seedu/address/logic/commands/reminder/DeleteReminderCommand.java
  src/main/java/seedu/address/logic/commands/reminder/EditReminderCommand.java
  src/main/java/seedu/address/logic/parser/ClientHubParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/reminder/AddReminderCommandParser.java
  src/main/java/seedu/address/logic/parser/reminder/AddReminderParser.java
  src/main/java/seedu/address/logic/parser/reminder/DeleteReminderCommandParser.java
  src/main/java/seedu/address/logic/parser/reminder/DeleteReminderParser.java
  src/main/java/seedu/address/logic/parser/reminder/EditReminderCommandParser.java
  src/main/java/seedu/address/model/ClientHub.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyClientHub.java
  src/main/java/seedu/address/model/reminder/Reminder.java
  src/main/java/seedu/address/model/reminder/ReminderDescription.java
  src/main/java/seedu/address/model/reminder/ReminderList.java
  src/main/java/seedu/address/model/reminder/ReminderNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/ClientHubTest.java
Labels: priority.High

#174 Refine FindClientTypeCommand
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindClientTypeCommand.java
  src/main/java/seedu/address/model/person/ClientTypeContainsKeywordsPredicate.java
  src/test/data/JsonSerializableClientHubTest/typicalPersonsClientHub.json
  src/test/java/seedu/address/logic/commands/FindClientTypeCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#176 Create a simple ReminderList UI
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ReminderCard.java
  src/main/java/seedu/address/ui/ReminderListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ReminderCard.fxml
  src/main/resources/view/ReminderListPanel.fxml
Labels: priority.Low

#178 Refine Personcard UI
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ViewPersonWindow.fxml
Labels: priority.Low

#181 Update Sample Data for CLientHub
  docs/images/Ui.png
  docs/images/helpMessage.png
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium

#182 Branch reminder add edit
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/reminder/AddReminderCommandParser.java
  src/main/java/seedu/address/model/ClientHub.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/reminder/Reminder.java
  src/main/java/seedu/address/model/reminder/ReminderDescription.java
Labels: priority.High

#183 Update UG and index.md
  docs/UserGuide.md
  docs/images/Find9103Result.png
  docs/images/FindClientType.png
  docs/images/FindInvestmentResult.png
  docs/images/FindRoyResult.png
  docs/images/FindTampinesResult.png
  docs/images/Ui.png
  docs/images/ViewCommandExample.png
  docs/images/find9234Result.png
  docs/images/findAlexDavidResult.png
  docs/images/findTampines.png
  docs/images/viewCommandExample.png
  docs/index.md
Labels: priority.Medium

#185 Fix the main Find Command for client types
  src/main/java/seedu/address/logic/parser/FindClientTypeCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
Labels: priority.Medium

#186 Add more testcases in ViewCommandParserTest
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: priority.Low

#188 Link Reminder logic to UI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
  src/main/java/seedu/address/model/reminder/Reminder.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ReminderCard.java
  src/main/java/seedu/address/ui/ReminderListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ReminderCard.fxml
Labels: priority.Medium

#189 Fix errors in UG
  docs/UserGuide.md
Labels: priority.Low

#191 Update reminder test
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/reminder/DeleteReminderCommand.java
  src/main/java/seedu/address/model/reminder/ReminderDescription.java
  src/test/java/seedu/address/logic/commands/reminder/AddReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/reminder/DeleteReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/reminder/EditReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/reminder/ReminderCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/reminder/AddReminderParserTest.java
  src/test/java/seedu/address/logic/parser/reminder/DeleteReminderParserTest.java
  src/test/java/seedu/address/logic/parser/reminder/EditReminderParserTest.java
  src/test/java/seedu/address/model/reminder/ReminderDescriptionTest.java
  src/test/java/seedu/address/model/reminder/ReminderListTest.java
  src/test/java/seedu/address/model/reminder/ReminderTest.java
  src/test/java/seedu/address/testutil/ReminderBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalReminders.java
Labels: priority.High

#203 Update Code to fix bug
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: alpha-bug
