Repository AY2425S1-CS2103T-F10-1/tp, pull requests merged in 2024-11, with the labels that each got.

#210 Branch add reminder field
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
  src/main/java/seedu/address/logic/commands/reminder/DeleteReminderCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/ClientHub.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/reminder/Reminder.java
  src/main/java/seedu/address/model/reminder/ReminderDescription.java
  src/main/java/seedu/address/model/reminder/ReminderList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedReminder.java
  src/main/java/seedu/address/storage/JsonSerializableClientHub.java
Labels: priority.High

#213 Fix the add reminder command
  src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
  src/main/java/seedu/address/model/reminder/Reminder.java
Labels: type.Bug, priority.High

#215 Update Reminder code
  src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
  src/main/java/seedu/address/logic/commands/reminder/DeleteReminderCommand.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#217 Branch fix testcases
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/reminder/ReminderDescriptionTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Bug, priority.High

#218 Update Json files
  src/main/java/seedu/address/model/ClientHub.java
  src/main/java/seedu/address/storage/JsonSerializableClientHub.java
  src/test/data/JsonClientHubStorageTest/invalidPersonClientHub.json
  src/test/data/JsonSerializableClientHubTest/duplicatePersonClientHub.json
  src/test/data/JsonSerializableClientHubTest/typicalPersonsClientHub.json
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/reminder/DeleteReminderCommandTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalReminders.java
Labels: priority.High

#219 Update md files for style
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/reminder/DeleteReminderCommandTest.java
  src/test/java/seedu/address/model/reminder/ReminderDescriptionTest.java
  src/test/java/seedu/address/testutil/TypicalReminders.java
Labels: priority.Low

#223 Minor UI fix to ReminderList
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.Low

#221 Fix EditCommand tests
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, priority.High, alpha-bug

#228 Add new TestCase for deletecommand
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: priority.Medium

#227 Fix AddReminder
  src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
Labels: type.Enhancement, type.Bug, priority.High

#232 Refine AddCommand
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Enhancement, priority.High, severity.High

#236 Update DeleteCommandParser
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
Labels: priority.Medium

#238 Add Command History feature
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Enhancement, priority.Low

#240 Changed persons to clients and follow the plurality
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindAddressCommand.java
  src/main/java/seedu/address/logic/commands/FindClientTypeCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindNameCommand.java
  src/main/java/seedu/address/logic/commands/FindPhoneCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/test/java/seedu/address/logic/commands/FindAddressCommandTest.java
  src/test/java/seedu/address/logic/commands/FindClientTypeCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindNameCommandTest.java
  src/test/java/seedu/address/logic/commands/FindPhoneCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
Labels: priority.Medium, severity.Medium

#239 Refine command output for FindCommand
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: type.Enhancement, priority.Medium

#241 Edit command fix
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/clienttype/ClientType.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/data/JsonSerializableClientHubTest/typicalPersonsClientHub.json
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/ClientTypeContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsDeletePredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, priority.Medium

#244 Fix the name displayed
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindAddressCommand.java
  src/main/java/seedu/address/logic/commands/FindClientTypeCommand.java
  src/main/java/seedu/address/logic/commands/FindNameCommand.java
  src/main/java/seedu/address/logic/commands/FindPhoneCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.Medium, severity.Medium

#248 Branch refine output message
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FindAddressCommand.java
  src/main/java/seedu/address/logic/commands/FindClientTypeCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindNameCommand.java
  src/main/java/seedu/address/logic/commands/FindPhoneCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: type.Enhancement, priority.High

#253 Add additional feature section into UserGuide
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#257 Update User guide
  docs/UserGuide.md
  src/test/java/seedu/address/logic/parser/ClientHubParserTest.java
Labels: priority.High

#260 Fix name field message
  src/main/java/seedu/address/model/person/Name.java
Labels: priority.Medium

#263 Update edit command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.Medium

#268 Sort reminder list
  src/main/java/seedu/address/logic/commands/reminder/EditReminderCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.Medium

#269 Branch fix view
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: priority.Medium

#272 Branch address constraint
  src/main/java/seedu/address/model/person/Address.java
Labels: priority.Medium

#274 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/AddReminderSequenceDiagram-Logic.puml
  docs/diagrams/AddReminderSequenceDiagram-Model.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
  src/main/java/seedu/address/storage/JsonSerializableClientHub.java
Labels: priority.Medium

#273 Branch fix user guide
  docs/UserGuide.md
  docs/images/result_for_add.png
  docs/images/result_for_add_reminder.png
  docs/images/result_for_delete.png
  docs/images/result_for_delete_reminder.png
  docs/images/result_for_edit.png
  docs/images/result_for_edit_reminder.png
  docs/images/result_for_find_address.png
  docs/images/result_for_find_clienttypes.png
  docs/images/result_for_find_name.png
  docs/images/result_for_find_phone.png
  docs/images/result_for_view.png
Labels: type.Enhancement, priority.Medium

#277 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: priority.Medium

#279 Update dg
  docs/DeveloperGuide.md
  docs/diagrams/AddReminderCommandActivityDiagram.puml
  docs/diagrams/AddReminderSequenceDiagram-Logic.puml
  docs/diagrams/AddReminderSequenceDiagram-Model.puml
  docs/images/AddReminderCommandActivity.png
  docs/images/AddReminderSequenceDiagram-Logic.png
  docs/images/AddReminderSequenceDiagram-Model.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: priority.High

#280 Update MainWindow UI
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.Low

#285 Update UserGuide
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#288 Update Name predicates
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindAddressCommand.java
  src/main/java/seedu/address/logic/commands/FindClientTypeCommand.java
  src/main/java/seedu/address/logic/commands/FindNameCommand.java
  src/main/java/seedu/address/logic/commands/FindPhoneCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsDeletePredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindAddressCommandTest.java
  src/test/java/seedu/address/logic/commands/FindClientTypeCommandTest.java
  src/test/java/seedu/address/logic/commands/FindNameCommandTest.java
  src/test/java/seedu/address/logic/commands/FindPhoneCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
Labels: priority.High

#289 Update DG
  docs/images/BetterModelClassDiagram.png
Labels: priority.High

#290 Fix a small bug in View
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.Medium

#291 Update dg
  docs/DeveloperGuide.md
Labels: priority.High

#292 Update DG
  docs/DeveloperGuide.md
Labels: priority.Low

#295 Update User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium

#297 Fix the date time format for reminder commands
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/model/reminder/Reminder.java
Labels: priority.High

#299 Fix edit reminder display message
  src/main/java/seedu/address/logic/commands/reminder/EditReminderCommand.java
  src/test/java/seedu/address/logic/commands/reminder/EditReminderCommandTest.java
Labels: priority.Low, severity.Low, alpha-bug

#300 Update UG for findclienttype section
  docs/UserGuide.md
Labels: type.Bug, priority.High

#349 Fix view bugs
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ViewPersonWindow.java
Labels: priority.High

#350 Refine UG
  docs/UserGuide.md
Labels: priority.Medium

#352 Fix parameter specification table
  docs/UserGuide.md
Labels: priority.Medium

#353 Update User and Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug

#356 Developer Guide Changes
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug

#357 Minor typo fix
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Description.java
Labels: priority.Medium

#358 Fix AddReminder Bug
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.High

#359 Revert the changes of the View Command fix
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ViewPersonWindow.java
Labels: priority.High

#360 Update help window and UG for consistency
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug, priority.Low, severity.Low, alpha-bug, type.UG-bug

#362 Update images for UG
  docs/images/result_for_add_reminder.png
  docs/images/result_for_delete_reminder.png
  docs/images/result_for_edit_reminder.png
Labels: type.UG-bug

#361 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#364 Refine DG
  docs/DeveloperGuide.md
Labels: priority.High

#366 Refine UG
  docs/UserGuide.md
Labels: priority.High

#367 Clean user guide
  docs/UserGuide.md
Labels: priority.High

#368 Update UG command summary table and help window
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug, priority.High, type.UG-bug

#369 Correct one of the sentences
  docs/UserGuide.md
Labels: priority.High

#370 Refine UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ClientHubMain.png
Labels: priority.High
